version: '3.7'
services:
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/nginx/conf.d:/etc/nginx/conf.d
      # default.conf
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/html:/usr/share/nginx/html
      - /opt/nginx/letsencrypt/live/yanxianhe.com/fullchain.pem:/etc/ssl/certs/server.crt
      - /opt/nginx/letsencrypt/live/yanxianhe.com/privkey.pem:/etc/ssl/private/server.key
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Shanghai
      - DNS_ADDRS=8.8.8.8,8.8.4.4
  certbot:
    hostname: v2certbot
    container_name: v2certbot
    image: registry.cn-beijing.aliyuncs.com/dockermg/v2certbot:v1.0.0
    environment:
      - TZ=Asia/Shanghai
      # 如果你的服务不是默认的 HTTP（80）和 HTTPS（443）端口，而是使用了其他端口 请设置 HTTP_PORT HTTPS_PORT 环境变量
      # - HTTP_PORT=80
      # - HTTPS_PORT=443
      - UPDATE_INTERVAL=86400
      - LET_MAILBOX=xianhe_yan@sina.com
      - DOMAIN_NAME=yanxianhe.com
    volumes:
      - /opt/html:/var/www/html
      - /opt/nginx/letsencrypt:/etc/letsencrypt
    entrypoint: sh /letsencrypt.sh 
    networks:
      - nginx_net
networks:
  nginx_net:

